/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redbrick.medright;

/**
 *
 * @author RedBrick
 */
public class ScheduleDataEntry extends javax.swing.JFrame {

    /**
     * Creates new form ScheduleDataEntry
     */
    public ScheduleDataEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SchedCreate = new javax.swing.JPanel();
        jlSceduleCreator = new javax.swing.JLabel();
        jcbSchedType = new javax.swing.JComboBox();
        jlSchedType = new javax.swing.JLabel();
        Monday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Thursday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        Sunday = new javax.swing.JCheckBox();
        AM = new javax.swing.JCheckBox();
        MidMorn = new javax.swing.JCheckBox();
        Noon = new javax.swing.JCheckBox();
        MidAft = new javax.swing.JCheckBox();
        Afternoon = new javax.swing.JCheckBox();
        Evening = new javax.swing.JCheckBox();
        Bedtime = new javax.swing.JCheckBox();
        jlName = new javax.swing.JLabel();
        jlCondition = new javax.swing.JLabel();
        jlDose = new javax.swing.JLabel();
        jcbSize = new javax.swing.JComboBox();
        Calendar = new javax.swing.JCheckBox();
        Reminders = new javax.swing.JCheckBox();
        Done = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jftfName = new javax.swing.JFormattedTextField();
        jftfDose = new javax.swing.JFormattedTextField();
        jftfCondition = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlSceduleCreator.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jlSceduleCreator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSceduleCreator.setText("Schedule Creator");
        jlSceduleCreator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcbSchedType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select  --", "Pill", "Liquid", "Topical", "Fitness", "Other" }));

        jlSchedType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlSchedType.setText("Schedule Type");

        Monday.setText("Monday");

        Tuesday.setText("Tuesday");
        Tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayActionPerformed(evt);
            }
        });

        Wednesday.setText("Wednesday");

        Thursday.setText("Thursday");

        Friday.setText("Friday");

        Saturday.setText("Saturday");

        Sunday.setText("Sunday");

        AM.setText("A.M.");

        MidMorn.setText("Mid-Morning");

        Noon.setText("Noon");

        MidAft.setText("Mid-Afternoon");

        Afternoon.setText("Afternoon");

        Evening.setText("Evening");

        Bedtime.setText("Bedtime");

        jlName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlName.setText(" Name of Medication, Treatment or Supplement");

        jlCondition.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCondition.setText("Condition/Reason");

        jlDose.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlDose.setText("  Amount  ");

        jcbSize.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jcbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select --", "Milligrams", "Milliliters", "Ounces", "Teaspoon", "Tablespoon", "Cups", "Application", "Grams" }));

        Calendar.setText(" Calendar Event");

        Reminders.setText(" Create Reminders");
        Reminders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemindersActionPerformed(evt);
            }
        });

        Done.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Done.setText("  Exit  ");
        Done.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Next.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Next.setText("  New  ");
        Next.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Save.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Save.setText("  Save  ");
        Save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("  Help  ");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(5);
        jButton1.setMargin(new java.awt.Insets(3, 14, 3, 14));

        jftfName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jftfName.setMinimumSize(new java.awt.Dimension(4, 21));
        jftfName.setPreferredSize(new java.awt.Dimension(4, 21));

        jftfDose.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jftfDose.setMinimumSize(new java.awt.Dimension(4, 21));
        jftfDose.setPreferredSize(new java.awt.Dimension(4, 21));

        jftfCondition.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jftfCondition.setMinimumSize(new java.awt.Dimension(4, 21));
        jftfCondition.setPreferredSize(new java.awt.Dimension(4, 21));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("  Measure  ");

        javax.swing.GroupLayout SchedCreateLayout = new javax.swing.GroupLayout(SchedCreate);
        SchedCreate.setLayout(SchedCreateLayout);
        SchedCreateLayout.setHorizontalGroup(
            SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchedCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(SchedCreateLayout.createSequentialGroup()
                            .addComponent(jlSceduleCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(369, 369, 369))
                        .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SchedCreateLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Done)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Next))
                            .addGroup(SchedCreateLayout.createSequentialGroup()
                                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SchedCreateLayout.createSequentialGroup()
                                        .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jlSchedType)
                                            .addComponent(jcbSchedType, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Saturday)
                                            .addComponent(Monday))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Sunday)
                                            .addGroup(SchedCreateLayout.createSequentialGroup()
                                                .addComponent(Tuesday)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Wednesday)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Thursday)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Friday))))
                                    .addGroup(SchedCreateLayout.createSequentialGroup()
                                        .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(SchedCreateLayout.createSequentialGroup()
                                                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jftfDose, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlDose))
                                                .addGap(10, 10, 10)
                                                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jcbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlCondition)
                                                    .addComponent(jftfCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jftfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(59, 59, 59)
                                        .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Reminders)
                                            .addComponent(Calendar))))
                                .addGap(17, 17, 17))))
                    .addComponent(jlName)
                    .addGroup(SchedCreateLayout.createSequentialGroup()
                        .addComponent(AM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MidMorn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Noon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MidAft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Afternoon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Evening)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bedtime)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SchedCreateLayout.setVerticalGroup(
            SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchedCreateLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlSceduleCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSchedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Monday)
                    .addComponent(Tuesday)
                    .addComponent(Wednesday)
                    .addComponent(Thursday)
                    .addComponent(Friday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSchedType)
                    .addComponent(Saturday)
                    .addComponent(Sunday))
                .addGap(21, 21, 21)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AM)
                    .addComponent(MidMorn)
                    .addComponent(Noon)
                    .addComponent(MidAft)
                    .addComponent(Afternoon)
                    .addComponent(Evening)
                    .addComponent(Bedtime))
                .addGap(18, 18, 18)
                .addComponent(jlName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reminders))
                .addGap(10, 10, 10)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDose, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCondition)
                    .addComponent(Calendar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(SchedCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Done)
                    .addComponent(Next)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SchedCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SchedCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemindersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemindersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemindersActionPerformed

    private void TuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleDataEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AM;
    private javax.swing.JCheckBox Afternoon;
    private javax.swing.JCheckBox Bedtime;
    private javax.swing.JCheckBox Calendar;
    private javax.swing.JButton Done;
    private javax.swing.JCheckBox Evening;
    private javax.swing.JCheckBox Friday;
    private javax.swing.JCheckBox MidAft;
    private javax.swing.JCheckBox MidMorn;
    private javax.swing.JCheckBox Monday;
    private javax.swing.JButton Next;
    private javax.swing.JCheckBox Noon;
    private javax.swing.JCheckBox Reminders;
    private javax.swing.JCheckBox Saturday;
    private javax.swing.JButton Save;
    private javax.swing.JPanel SchedCreate;
    private javax.swing.JCheckBox Sunday;
    private javax.swing.JCheckBox Thursday;
    private javax.swing.JCheckBox Tuesday;
    private javax.swing.JCheckBox Wednesday;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jcbSchedType;
    private javax.swing.JComboBox jcbSize;
    private javax.swing.JFormattedTextField jftfCondition;
    private javax.swing.JFormattedTextField jftfDose;
    private javax.swing.JFormattedTextField jftfName;
    private javax.swing.JLabel jlCondition;
    private javax.swing.JLabel jlDose;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSceduleCreator;
    private javax.swing.JLabel jlSchedType;
    // End of variables declaration//GEN-END:variables
}
