INSERT INTO guid VALUES (0,"PILL");
INSERT INTO guid VALUES (100,"LIQUID");
INSERT INTO guid VALUES (200,"TOPICAL");
INSERT INTO guid VALUES (300,"INJECTION");
INSERT INTO guid VALUES (400,"SUPPLEMENT");

